jobs:
- command: [ls, pwd]
  cron: '@every 20s'
  env: [MONGOPORT=27017]
  mail: null
  name: job-api
  retry_cnt: 3
  retry_time: 5
  # 接口请求超时时间，单位s
  request_timout: 5
  # 接口请求返回异常状态. 默认包含500/404
  request_status: []
  url: http://47.91.255.0/api/index
mail:
  mail_subject: ''
  mail_to: [huoyinghui@apkpure.net]
  smtp_host: smtp.zoho.com:465
  smtp_passwd: pass
  smtp_tls: true
  smtp_user: user
timezone: Asia/Shanghai
